language: node_js
node_js:
  - '0.12.2'
install:
  - npm cache clean
  - npm install
  - npm install -g yo
  - npm install -g .
  - npm install -g grunt-cli
  - npm install -g bower
script:
  - npm test
  - mkdir testAppDir && cd testAppDir
  - echo Y | yo angular-blueprint myApp
  - grunt
notifications:
  email:
    - dannybluedesign@gmail.com
