language: node_js
node_js:
  - '0.12.2'
script:
  - npm test
  - npm install -g yo
  - npm install -g .
  - rm -rf testAppDir
  - mkdir testAppDir && cd testAppDir
  - yo angular-blueprint myApp | xargs echo -0
notifications:
  email:
    - dannybluedesign@gmail.com
