language: node_js
node_js:
  - '0.12.2'
install:
  - npm install
  - npm install -g yo
  - npm install -g .
  - npm install -g bower
script:
  - sh test.sh
notifications:
  email:
    - dannybluedesign@gmail.com
