language: node_js
node_js:
  - '0.12.2'
script:
  - npm test
  - npm install -g yo
  - npm install -g .
  - yo angular-blueprint myApp | xargs echo
notifications:
  email:
    - dannybluedesign@gmail.com
